model: 
   path: /home/ruslan/Faces/FaceNet/models/20200724-231357
multi_face_validation: 
   batch_size: 5
   moving_average_decay: 0.9999
   nrof_epochs: 1000
dataset: 
   path: /media/a/datasets/megaface/megaface_frcnnv3extracted_160
   h5file: /media/a/datasets/megaface/megaface_frcnnv3extracted_160_20190727-080213.h5
   nrof_classes: None
   max_nrof_images: 50
   min_nrof_images: 1
validate: 
   nrof_folds: 10
   metric: 0
   far_target: 0.001
image: 
   size: 160
   standardization: True
   use_flipped_images: False
seed: 0
file: /home/ruslan/Faces/FaceNet/models/20200724-231357/report.txt
batch_size: 64

model: 
   path: /home/ruslan/Faces/FaceNet/models/20200724-231357
multi_face_validation: 
   batch_size: 5
   moving_average_decay: 0.9999
   nrof_epochs: 1000
dataset: 
   path: /media/a/datasets/megaface/megaface_frcnnv3extracted_160
   h5file: /media/a/datasets/megaface/megaface_frcnnv3extracted_160_20190727-080213.h5
   nrof_classes: None
   max_nrof_images: 50
   min_nrof_images: 1
validate: 
   nrof_folds: 10
   metric: 0
   far_target: 0.001
image: 
   size: 160
   standardization: True
   use_flipped_images: False
seed: 0
file: /home/ruslan/Faces/FaceNet/models/20200724-231357/report.txt
batch_size: 64

model: 
   path: /home/ruslan/Faces/FaceNet/models/20200724-231357
multi_face_validation: 
   batch_size: 5
   moving_average_decay: 0.9999
   nrof_epochs: 1000
dataset: 
   path: /media/a/datasets/megaface/megaface_frcnnv3extracted_160
   h5file: /media/a/datasets/megaface/megaface_frcnnv3extracted_160_20190727-080213.h5
   nrof_classes: None
   max_nrof_images: 50
   min_nrof_images: 1
validate: 
   nrof_folds: 10
   metric: 0
   far_target: 0.001
image: 
   size: 160
   standardization: True
   use_flipped_images: False
seed: 0
file: /home/ruslan/Faces/FaceNet/models/20200724-231357/report.txt
batch_size: 64

model: 
   path: /home/ruslan/Faces/FaceNet/models/20200724-231357
multi_face_validation: 
   batch_size: 5
   moving_average_decay: 0.9999
   nrof_epochs: 1000
dataset: 
   path: /media/a/datasets/megaface/megaface_frcnnv3extracted_160
   h5file: /media/a/datasets/megaface/megaface_frcnnv3extracted_160_20190727-080213.h5
   nrof_classes: None
   max_nrof_images: 50
   min_nrof_images: 1
validate: 
   nrof_folds: 10
   metric: 1
   far_target: 0.001
image: 
   size: 160
   standardization: True
   use_flipped_images: False
seed: 0
file: /home/ruslan/Faces/FaceNet/models/20200724-231357/report.txt
batch_size: 64

