# coding:utf-8

# Random seed
seed: 0

# Number of images to process in a batch.
batch_size: 100

model:
  # Path to default directory containing the meta_file and ckpt_file or a model protobuf (.pb) file,
  # if path is not defined default_model_path from config.py will be used
  path:
  # If true normalize output embeddings to 1
  normalize: false


embeddings:
  # path to input data file
  path: ~/datasets/vggface2/test_extracted_160_default/embeddings.h5
  # Number of classes to download from h5 file
  nrof_classes:
  # Number of images to download from h5 file
  max_nrof_images: 50
  # Normalize embeddings
  normalize: false


image:
  # Image size (height, width) in pixels
  size: 160
  # Margin for the crop around the bounding box (height, width) in pixels
  margin: 0
  # Performs normalization of the input images
  normalization: 0
