# coding:utf-8

# Random seed
seed: 0

# Number of images to process in a batch.
batch_size: 100

image:
  # Image size (height, width) in pixels.
  size: 160
  # Performs normalization of images
  normalization: 0

# Model definition
model:
  # Directory where to write trained models and checkpoints
  path: ~/models/facenet
  # Load a pretrained checkpoint before training starts.
  checkpoint:
