# coding:utf-8

# Random seed
seed: 0

# Number of images to process in a batch.
batch_size: 100

# Image definition
image:
  # Image size (height, width) in pixels
  size: 160
  # Margin for the crop around the bounding box (height, width) in pixels
  margin: 0
  # Performs normalization of the input images
  normalization: 0

# Model definition
model:
  # Module containing the definition of the inference graph
  module: facenet.models.inception_resnet_v1
  # Load a pretrained checkpoint before training starts.
  checkpoint:
  # Directory where to write trained models and checkpoints
  path: ~/models/facenet
