# coding:utf-8

# Path to directory containing the meta_file and ckpt_file or a model protobuf (.pb) file
model:
  path:
  normalize: false

# type of the output file (h5 or tfrecord)
output: h5

dataset:
  # Path to the directory with aligned face images to train facenet.
  path:
  # Path to h5 file with information about valid images.
  h5file:
  # Number of classes to download from data set
  nrof_classes:
  # Minimal number of images per class to download from class
  min_nrof_images:
  # Maximal number of images per class to download from class
  max_nrof_images:

image:
  # Image size (height, width) in pixels.
  size:
  # Performs normalization of the input images
  normalization: 0


