# coding:utf-8

# Could be either a directory containing the meta_file and ckpt_file or a model protobuf (.pb) file
model:

# Number of images to process in a batch
batch_size: 100

# Path to output tf record file
tfrecord:

dataset:
  # Path to the data directory containing aligned face patches
  path:
  # Path to h5 file with information about valid images
  h5file:
  # Minimal number of classes per class to download from data set
  min_nrof_images:
  # Maximal number of classes per class to download from data set
  max_nrof_classes:

image:
  # Image size (height, width) in pixels.
  size: 160
  # Performs standardization of images
  standardization: true
  # Concatenates embeddings for the image and its horizontally flipped counterpart
  use_flipped_images: false


