# coding:utf-8

# type of the output file (h5 or tfrecord)
suffix: .h5

dataset:
  # Path to the directory with aligned face images to train facenet.
  path: ~/datasets/vggface2/test_extracted_160
  # Number of classes to download from data set
  nrof_classes:
  # Minimal number of images per class to download from class
  min_nrof_images:
  # Maximal number of images per class to download from class
  max_nrof_images:

model:
  # Path to directory containing the meta_file and ckpt_file or a model protobuf (.pb) file, if
  # path is not defined default_model_path from config.py will be used
  path:
  # If true embeddings will be normalized to 1
  normalization: false

