# coding:utf-8

# type of the output file (h5 or tfrecord)
suffix: .h5

dataset:
  # Path to the directory with aligned face images to train facenet.
  path: ~/datasets/vggface2/test_extracted_160
  # Number of classes to download from data set
  nrof_classes:
  # Minimal number of images per class to download from class
  min_nrof_images:
  # Maximal number of images per class to download from class
  max_nrof_images:

image:
  # Image size (height, width) in pixels.
  size:
  # Performs normalization of the input images
  normalization:


