# coding:utf-8

# Path to directory containing the meta_file and ckpt_file or a model protobuf (.pb) file
model:
  path:
  normalize: false

# type of the output file (h5 or tfrecord)
output: h5

dataset:
  # Path to the data directory containing aligned face patches
  path:
  # Path to h5 file with information about valid images
  h5file:
  # Minimal number of classes per class to download from data set
  min_nrof_images:
  # Maximal number of classes per class to download from data set
  max_nrof_classes:

image:
  # Image size (height, width) in pixels.
  size:
  # Performs normalization of the input images
  normalization: 0


