# coding:utf-8

model:
  # Path to directory containing the trained model
  path:

dataset:
  # Path to the directory with aligned face images to train facenet.
  path: ~/datasets/megaface/megaface_extracted_160
  # Number of classes to download from data set
  nrof_classes:
  # Minimal number of images per class to download from class
  min_nrof_images:
  # Maximal number of images per class to download from class
  max_nrof_images:


outdir: