# coding:utf-8

# Directory to dataset with unaligned images.
dataset:
  path: ~/datasets/vggface2/train

# Directory to output extracted face thumbnails.
outdir:

# Detector to extract faces, pypimtcnn or frcnnv3, default is frcnnv3
detector: frcnnv3
