# coding:utf-8

nrof_classes_per_batch:

nrof_examples_per_class: 5

embeddings:
  # path to input data file
  path: ~/datasets/megaface/megaface_frcnnv3extracted_16020201008-183421.h5
  # Number of classes to download from h5 file
  nrof_classes:
  # Number of images to download from h5 file
  max_nrof_images: 50
  # Normalize embeddings
  normalize: false

# Model definition
classifier:
  # Directory where to write trained models and checkpoints
  path: ~/models/facenet/classifier

train:
  # The optimization algorithm to use
  optimizer: ADAM
  # Exponential decay for tracking of training parameters
  moving_average_decay: 0.9999

  # Number of batches per epoch.
  epoch:
    max_nrof_epochs: 2   # Maximal number of epochs to run
    size: 250            # Number of batches per epoch.

  # learning rate schedule
  learning_rate_schedule:
    initial_value: 0.01
    decay_rate:  0.1

#image:
#  # Image size (height, width) in pixels.
#  size: 160
#  # Performs fixed standardization of images
#  normalization: 0
#  # Performs random cropping of training images. If false, the center image_size pixels from
#  # the training images are used. If the size of the images in the data directory is equal to image_size no cropping is performed.
#  random_crop: false
#  # Performs random horizontal flipping of training images
#  random_flip: false
#  # Performs random rotations of training images
#  random_rotate: false
