# coding:utf-8

dataset:
  # Path to the directory with aligned face images to train facenet.
  path: ~/datasets/megaface/megaface_extracted_160
  # Number of classes to download from data set
  nrof_classes:
  # Minimal number of images per class to download from class
  min_nrof_images:
  # Maximal number of images per class to download from class
  max_nrof_images:

model:
  # Path to directory containing the meta_file and ckpt_file or a model protobuf (.pb) file, if
  # path is not defined default_model_path from config.py will be used
  path: ~/models/facenet

train:
  nrof_classes_per_batch: 8
  nrof_examples_per_class: 8

  # Number of batches per epoch.
  epoch:
    # Number of steps per epoch.
    size: 1000
    # Maximal number of epochs
    max_nrof_epochs:

  # learning rate schedule
  learning_rate:
    # Learning rate value
    value:

    # Learning rate schedule is used if value is not specified
    schedule:
      - [10, 0.01]
      - [20, 0.001]
      - [30, 0.0001]

embeddings:
  path: ~/models/facenet/20210124-092137/megaface_extracted_160/embeddings.h5
