# coding:utf-8

train:
  dataset:
    # Path to the directory with aligned face images to train facenet.
    path: ~/datasets/vggface2/train_extracted_160
    # Number of classes to download from data set
    nrof_classes:
    # Minimal number of images per class to download from class
    min_nrof_images:
    # Maximal number of images per class to download from class
    max_nrof_images:

  # Number of batches per epoch.
  epoch:
    # Maximal number of epochs to train facenet
    max_nrof_epochs:
    # Number of batches per epoch.
    size: 1000

  # learning rate value or schedule file
  learning_rate:
    # Learning rate value
    value:
    # Learning rate schedule is used if value is not specified
    schedule: [[50, 0.05], [100, 0.005], [150, 0.0005]]

## Config for validation
validate:
  dataset:
    # Path to the directory with aligned face images to validate facenet.
    path: ~/datasets/megaface/megaface_extracted_160
    # Number of classes to download from data set
    nrof_classes:
    # Minimal number of images per class to download from class
    min_nrof_images:
    # Maximal number of images per class to download from class
    max_nrof_images:

  # Number of folds to use for cross validation. Mainly used for testing
  nrof_folds: 10

  # Target false alarm rate (face pairs that was incorrectly classified as the same)
  far_target: 0.001