# coding:utf-8

dataset:
  # Directory with aligned face patches.
  path: ~/datasets/vggface2/test_frcnnv3extracted_160
  # Path to h5 file with information about valid images.
  h5file: None
  # Number of images to download from data set
  nrof_images: None
  # Number of classes to download from data set
  nrof_classes: None

# Model definition
model:
  # module containing the definition of the inference graph.',
  module: facenet.models.inception_resnet_v1
  # Model config
  config: None

# Directory where to write trained models and checkpoints
model_dir: ~/models/facenet/test

# Directory where to write event logs
log_dir: None

# Random seed
seed: 0

# The ratio of the total dataset to use for validation
validation_set_split_ratio: 0

# Classes with fewer images will be removed from the validation set
min_nrof_val_images_per_class: 0

# Load a pretrained checkpoint before training starts.
pretrained_checkpoint: None

# Number of images to process in a batch.
batch_size: 100

# Number of batches per epoch.
epoch:
  size: 2            # Number of batches per epoch.
  max_nrof_epochs: 2  # Maximal number of epochs to run

# Norm to use for prelogits norm loss.
prelogits_norm_p: 1.0

prelogits_norm_loss_factor: 0.0 # Loss based on the norm of the activations in the prelogits layer
center_loss_alfa: 0.95          # Center update rate for center loss
center_loss_factor: 0.0         # Center loss factor

# The optimization algorithm to use
optimizer: ADAM

# learning rate value or schedule file
learning_rate:
  # Initial learning rate. If set to a negative value a learning rate schedule can be specified in the file learning_rate_schedule.txt
  value: -1
  # File containing the learning rate schedule that is used when learning_rate is set to to -1
  schedule_file: data/learning_rate_schedule.txt
  # Number of epochs between learning rate decay
  decay_epochs: 100
  # Learning rate decay factor
  decay_factor: 1.0

moving_average_decay: 0.9999    # Exponential decay for tracking of training parameters
log_histograms: False           # Enables logging of weight/bias histograms in tensorboard


gpu_memory_fraction: 1.0        # Upper bound on the amount of GPU memory that will be used by the process

validate_every_n_epochs: 10     # Number of epoch between validation

image:
  # Image size (height, width) in pixels.
  size: 160
  # Performs fixed standardization of images
  standardization: true
  # Performs random cropping of training images. If false, the center image_size pixels from
  # the training images are used. If the size of the images in the data directory is equal to image_size no cropping is performed.
  random_crop: false
  # Performs random horizontal flipping of training images
  random_flip: false
  # Performs random rotations of training images
  random_rotate: false

prelogits_hist_max: 10.0 # The max value for the prelogits histogram

nrof_preprocess_threads: 4 # Number of preprocessing (data loading and augmentation)

# Config for validation
validation:
  # Directory containing the meta_file and ckpt_file or a model protobuf (.pb) file
  model: None

  # Number of images to process in a batch
  batch_size: 100

  dataset:
    # Path to the data directory containing aligned face patches
    path: none
    # Path to h5 file with information about valid images
    h5file: none
    # Number of classes to download from data set
    nrof_classes: 5
    # Maximal number of images to download from class
    nrof_images: 10

  validation:
    # Number of folds to use for cross validation. Mainly used for testing
    nrof_folds: 10
    # Distance metric  0: euclidean, 1: cosine similarity
    metric: 0
    # Target false alarm rate (face pairs that was incorrectly classified as the same)
    far_target: 0.001
    # File to write statistical report
    file: none

  image:
    # Performs standardization of images
    standardization: true
    # Concatenates embeddings for the image and its horizontally flipped counterpart
    use_flipped_images: false
    # Image size (height, width) in pixels.
    size: 160
