# coding:utf-8

dataset:
  path: none
  # Path to h5 file with information about valid images.
  h5file: none
  # Number of classes to download from data set
  nrof_classes: none
  # Maximal number of images to download from class
  nrof_images: none

# Model definition
model:
  # module containing the definition of the inference graph.',
  module: facenet.models.inception_resnet_v1
  # Model config
  config: none
  # Load a pretrained checkpoint before training starts.
  checkpoint: none
  # Directory where to write trained models and checkpoints
  path: ~/models/facenet/softmax

# Random seed
seed: 0

# The ratio of the total dataset to use for validation
validation_set_split_ratio: 0

# Classes with fewer images will be removed from the validation set
min_nrof_val_images_per_class: 0

# Number of images to process in a batch.
batch_size: 100

# Number of batches per epoch.
epoch:
  # Number of batches per epoch.
  size: 2
  # Maximal number of epochs to run
  max_nrof_epochs: 1000

# Norm to use for prelogits norm loss.
prelogits_norm_p: 1.0

prelogits_norm_loss_factor: 0.0 # Loss based on the norm of the activations in the prelogits layer
center_loss_alfa: 0.95          # Center update rate for center loss
center_loss_factor: 0.0         # Center loss factor

# The optimization algorithm to use
optimizer: ADAM

# learning rate value or schedule file
learning_rate:
  # Initial learning rate value
  value: none
  # Number of epochs between learning rate decay
  decay_epochs: 100
  # Learning rate decay factor
  decay_factor: 1.0
  # Learning rate schedule that is used when value is none
  schedule:
    - [100, 0.05]
    - [200, 0.005]
    - [300, 0.0005]

moving_average_decay: 0.9999    # Exponential decay for tracking of training parameters

log_histograms: False           # Enables logging of weight/bias histograms in tensorboard

gpu_memory_fraction: 1.0        # Upper bound on the amount of GPU memory that will be used by the process

validate_every_n_epochs: 10     # Number of epoch between validation

image:
  # Image size (height, width) in pixels.
  size: 160
  # Performs fixed standardization of images
  standardization: true
  # Performs random cropping of training images. If false, the center image_size pixels from
  # the training images are used. If the size of the images in the data directory is equal to image_size no cropping is performed.
  random_crop: false
  # Performs random horizontal flipping of training images
  random_flip: false
  # Performs random rotations of training images
  random_rotate: false

prelogits_hist_max: 10.0 # The max value for the prelogits histogram

nrof_preprocess_threads: 4 # Number of preprocessing (data loading and augmentation)

# Config for validation
validation:
  # Number of images to process in a batch
  batch_size: 100

  dataset:
    # Path to the data directory containing aligned face patches
    path: none
    # Path to h5 file with information about valid images
    h5file: none
    # Number of classes to download from data set
    nrof_classes: none
    # Maximal number of images to download from class
    nrof_images: none

  validation:
    # Number of folds to use for cross validation. Mainly used for testing
    nrof_folds: 10
    # Distance metric  0: euclidean, 1: cosine similarity
    metric: 0
    # Target false alarm rate (face pairs that was incorrectly classified as the same)
    far_target: 0.001
    # File to write statistical report
    file: none

  image:
    # Image size (height, width) in pixels.
    size: 160
    # Performs standardization of images
    standardization: true
    # Concatenates embeddings for the image and its horizontally flipped counterpart
    use_flipped_images: false
