# coding:utf-8

# Random seed
seed: 0

# Number of images to process in a batch.
batch_size: 100

dataset:
  path:
  # Path to h5 file with information about valid images.
  h5file:
  # Number of classes to download from data set
  nrof_classes:
  # Minimal number of images per class to download from class
  min_nrof_images:
  # Maximal number of images per class to download from class
  max_nrof_images:

# Model definition
model:
  # module containing the definition of the inference graph.',
  module: facenet.models.inception_resnet_v1
  # Model config
  config:
  # Load a pretrained checkpoint before training starts.
  checkpoint:
  # Directory where to write trained models and checkpoints
  path: ~/models/facenet/softmax

train:
  # The optimization algorithm to use
  optimizer: ADAM
  # Exponential decay for tracking of training parameters
  moving_average_decay: 0.9999
  # Enables logging of weight/bias histograms in tensorboard
  log_histograms: false

  # Number of batches per epoch.
  epoch:
    # Number of batches per epoch.
    size: 1000
    # Maximal number of epochs to run
    nrof_epochs: 1000

  # learning rate value or schedule file
  learning_rate:
    # Initial learning rate value
    value:
    # Number of epochs between learning rate decay
    decay_epochs: 100
    # Learning rate decay factor
    decay_factor: 1.0
    # Learning rate schedule that is used when value is none
    schedule:
      - [100, 0.05]
      - [200, 0.005]
      - [300, 0.0005]

loss:
  prelogits_norm_p: 1.0       # Norm to use for prelogits norm loss.
  prelogits_hist_max: 10.0    # The max value for the prelogits histogram
  prelogits_norm_factor: 0.0  # Loss based on the norm of the activations in the prelogits layer
  center_alfa: 0.95           # Center update rate for center loss
  center_factor: 0.0          # Center loss factor

image:
  # Image size (height, width) in pixels.
  size: 160
  # Performs fixed standardization of images
  standardization: true
  # Performs random cropping of training images. If false, the center image_size pixels from
  # the training images are used. If the size of the images in the data directory is equal to image_size no cropping is performed.
  random_crop: false
  # Performs random horizontal flipping of training images
  random_flip: false
  # Performs random rotations of training images
  random_rotate: false


# Config for validation
validate:
  # Number of epoch between validation
  every_n_epochs: 10

  # Split validate data set from train data set
  split_ratio: 0.05

  dataset:
    # Path to the data directory containing aligned face patches
    path:
    # Path to h5 file with information about valid images
    h5file:
    # Number of classes to download from data set
    nrof_classes:
    # Minimal number of images per class to download from class
    min_nrof_images:
    # Maximal number of images per class to download from class
    max_nrof_images: 50

  validate:
    # Distance metric  0: euclidean, 1: cosine similarity
    metric: 1
    # Number of folds to use for cross validation. Mainly used for testing
    nrof_folds: 10
    # Target false alarm rate (face pairs that was incorrectly classified as the same)
    far_target: 0.001
    # File to write statistical report
    file:

  image:
    # Concatenates embeddings for the image and its horizontally flipped counterpart
    use_flipped_images: false

gpu_memory_fraction: 1.0        # Upper bound on the amount of GPU memory that will be used by the process
