# coding:utf-8

# number of classes per batch, if None each class will be used
nrof_classes_per_batch:

# number of images per batch to define pipeline batch
nrof_examples_per_class: 5

# Model definition
classifier:
  # Directory where to write output logs
  path: ~/models/facenet/classifier

train:
  # The optimization algorithm to use
  optimizer: ADAM
  # Exponential decay for tracking of training parameters
  moving_average_decay: 0.9999

  # Number of batches per epoch.
  epoch:
    max_nrof_epochs: 2   # Maximal number of epochs to run
    size: 250            # Number of batches per epoch.

  # learning rate schedule
  learning_rate_schedule:
    initial_value: 0.01
    decay_rate:  0.1

embeddings:
  # path to input data file
  path: ~/datasets/vggface2/test_extracted_160_default/embeddings.h5
  # Number of classes to download from input file
  nrof_classes:
  # Maximal number of embeddings to download from input file
  max_nrof_images: 50
  # Normalize embeddings
  normalize: false
