# coding:utf-8

model:
  # Directory containing the meta_file and ckpt_file or a model protobuf (.pb) file
  path:
  # If true normalize output embeddings to 1
  normalize:

dataset:
  # Path to the data directory containing aligned face patches
  path:
  # Path to h5 file with information about valid images
  h5file:
  # Number of classes to download from data set
  nrof_classes:
  # Minimal number of classes per class to download from data set
  min_nrof_images:
  # Maximal number of classes per class to download from data set
  max_nrof_images:

validate:
  # Number of folds to use for cross validation. Mainly used for testing
  nrof_folds: 10
  # Distance metric  0: euclidean, 1: cosine similarity
  metric: 0
  # Target false alarm rate (face pairs that was incorrectly classified as the same)
  far_target: 0.001

image:
  # Image size (height, width) in pixels.
  size:
  # Performs normalization of the input images
  normalization:


