# coding:utf-8

# Could be either a directory containing the meta_file and ckpt_file or a model protobuf (.pb) file
model: None

# Image size (height, width) in pixels.
image_size: 160

# Number of images to process in a batch
batch_size: 100

# File to write statistical report
report: None


dataset:
  # Path to the data directory containing aligned face patches
  path: None
  # Path to h5 file with information about valid images
  h5file: None
  # Portion of samples to download from data set
  portion: 1


validation:
  nrof_folds: 10            # Number of folds to use for cross validation. Mainly used for testing
  metric: 0                 # Distance metric  0: euclidean, 1: cosine similarity
  subtract_mean: false      # Subtract feature mean before calculating distance
  far_target: 0.001

image:
  # Performs standardization of images
  standardization: true
  # Concatenates embeddings for the image and its horizontally flipped counterpart
  use_flipped_images: false


