# coding:utf-8

# Directory containing the meta_file and ckpt_file or a model protobuf (.pb) file
model:

# Number of images to process in a batch
batch_size: 100

seed: 0

dataset:
  # Path to the data directory containing aligned face patches
  path:
  # Path to h5 file with information about valid images
  h5file:
  # Number of classes to download from data set
  nrof_classes:
  # Minimal number of classes per class to download from data set
  min_nrof_images: 1
  # Maximal number of classes per class to download from data set
  max_nrof_images:

validate:
  # File to write statistical report
  file: none
  # Number of folds to use for cross validation. Mainly used for testing
  nrof_folds: 10
  # Distance metric  0: euclidean, 1: cosine similarity
  metric: 1
  # Target false alarm rate (face pairs that was incorrectly classified as the same)
  far_target: 0.001

image:
  # Performs standardization of images
  standardization: true
  # Concatenates embeddings for the image and its horizontally flipped counterpart
  use_flipped_images: false
  # Image size (height, width) in pixels.
  size: 160


