# coding:utf-8

dataset:
  # Path to the data directory containing aligned face patches
  path: ~/datasets/vggface2/test_extracted_160
  # Path to h5 file with information about valid images
  h5file:
  # Number of classes to download from data set
  nrof_classes:
  # Minimal number of classes per class to download from data set
  min_nrof_images:
  # Maximal number of classes per class to download from data set
  max_nrof_images:

validate:
  # Number of folds to use for cross validation. Mainly used for testing
  nrof_folds: 10
  # Distance metric  0: euclidean, 1: cosine similarity
  metric: 0
  # Target false alarm rate (face pairs that was incorrectly classified as the same)
  far_target: 0.001
