# coding:utf-8

# Directory containing the meta_file and ckpt_file or a model protobuf (.pb) file
model: none

# Number of images to process in a batch
batch_size: 100

dataset:
  # Path to the data directory containing aligned face patches
  path: None
  # Path to h5 file with information about valid images
  h5file: None
  # Number of classes to download from data set
  nrof_classes: None
  # Maximal number of images to download from class
  nrof_images: None

validation:
  # Number of folds to use for cross validation. Mainly used for testing
  nrof_folds: 10
  # Distance metric  0: euclidean, 1: cosine similarity
  metric: 0
  # Target false alarm rate (face pairs that was incorrectly classified as the same)
  far_target: 0.001
  # File to write statistical report
  file: none

image:
  # Performs standardization of images
  standardization: true
  # Concatenates embeddings for the image and its horizontally flipped counterpart
  use_flipped_images: false
  # Image size (height, width) in pixels.
  size: 160


