---
# inception resnet v1 config
model_def: facenet.models.inception_resnet_v2

model_config:
  embedding_size: 512

# Keep probability of dropout for the fully connected layer(s).
  keep_probability: 1.0

# L2 weight regularization.
  weight_decay: 0.0

