---
# inception resnet v1 config
model_def: facenet.models.inception_resnet_v2

model_config:
  mixed_5a:
    branch: [[96], [48, 64], [64, 96, 96], [64]]

  mixed_6a:
    branch: [[384], [256, 256, 384]]

  mixed_7a:
    branch: [[256, 384], [256, 288], [256, 288, 320]]

  repeat: [10, 20, 9]

  embedding_size: 512

# Keep probability of dropout for the fully connected layer(s).
  keep_probability: 1.0

# L2 weight regularization.
  weight_decay: 0.0

