---
# inception resnet v1 config
model_def: facenet.models.inception_resnet_v1

model_config:
  reduction_a:
    k: 192
    l: 192
    m: 256
    n: 384

  repeat_block35: 5
  repeat_b: 10

  repeat_block8: 5

  embedding_size: 512

# Keep probability of dropout for the fully connected layer(s).
  keep_probability: 1.0

# L2 weight regularization.
  weight_decay: 0.0

